### ISSUE TITLE
Install fails: No targets specified and no makefile found. Stop.

### ISSUE THREAD

**Issue by barnumbirr** [Fleshgrinder/opentracker-compile#1]
Hi there,

just tried your script but the installation fails:

```
[root@host src]# sh opentracker/compile.sh
Installing opentracker with libowfat 0.29 ...
Updating package sources ...
Installing build dependencies ...
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version.
bzip2 is already the newest version.
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
Already up-to-date.
make: *** No targets specified and no makefile found.  Stop.
```

Cheers

**Comment by Fleshgrinder** [comment]
Hi, this was not the first run, right? Could you dump an `ls -l` of the checked out opentracker directory? Obviously the makefile was not found. Thanks for reporting! :+1:

**Comment by barnumbirr** [comment]
Hi,

here's the whole output: http://paste.calypso.pm/oVXfZuPZ

ls -la returns:

```
[root@calypso opentracker]# ls -la
total 48K
drwxr-sr-x 3 root 4.0K Feb  5 11:05 ./
drwxrwsr-x 4 root 4.0K Feb  5 11:05 ../
-rw-r--r-- 1 root 6.1K Feb  5 11:05 compile.sh
-rw-r--r-- 1 root  221 Feb  5 11:05 .editorconfig
drwxr-sr-x 8 root 4.0K Feb  5 11:05 .git/
-rw-r--r-- 1 root   19 Feb  5 11:05 .gitattributes
-rw-r--r-- 1 root    6 Feb  5 11:05 .gitignore
-rw-r--r-- 1 root 5.3K Feb  5 11:05 opentracker
-rw-r--r-- 1 root  395 Feb  5 11:05 README.md
-rw-r--r-- 1 root 1.2K Feb  5 11:05 UNLICENSE
```

Thank you.

**Comment by Fleshgrinder** [comment]
Do you have my repository in `/usr/local/src`? I think that this is the problem. I'll rename my repository to `opentracker-compile` in order to avoid this problem. Could you try again after renameing it as well if you have it in `/usr/local/src`?

It reports at the end that the repository is up to date (of course, since you just cloned it) and that it couldn't find a Makefile (of course, since my repository does not contain one).

**Comment by barnumbirr** [comment]
I did indeed clone opentracker to `/usr/local/src`. I've now move to repo to `opentracker-compile`but I'm still running into some issues:

http://paste.calypso.pm/gE9F5Qrw

When I do `service opentracker start`after I've created a config file, nothing happens. Seems that the command just loops forever.

**Comment by Fleshgrinder** [comment]
That was my fault with the last commit. This should fix all your issues together with the renamed repository.

**Comment by barnumbirr** [comment]
Still failing (hangs at 
`[FAIL] opentracker not found! ... failed!
install -m 755 opentracker /usr/local/sbin`)

http://paste.calypso.pm/i3xal5Lb

**EDIT:** Forgot to mention that I deleted `/usr/local/sbin/opentracker`and everything in `/usr/local/src`beforehand.

**Comment by Fleshgrinder** [comment]
Okay, that one is interesting. I have to set up a new Linux and debug it. I'll get back to you asap.

**Comment by barnumbirr** [comment]
No worries, thank you for your commitment to open-source software :+1:

**Comment by Fleshgrinder** [comment]
It was actually a _false positive_ because I try to stop the service before I attempt to install, the shell redirect was only catching the `STDERR` output, but the script was actually printing to `STDOUT`.

I tested it on a very limited and old Debian Linux, it compiled like a charm after I added `zlib1g-dev` to the build dependencies and removed the `-m64` flag from the compiler options (now added if the OS reports to be x64).

Thank you for reporting the issues. It makes me happy to see that people can benefit from what I do. :+1:

**Comment by barnumbirr** [comment]
Well, bummer:

http://paste.calypso.pm/SbRxqE59

Host system is running `Wheezy 7.7` along with kernel `3.16.0-0.bpo.4-amd64`.
Sorry for all the trouble. You're the one that should be thanked for your hard work, not me. :)

**Comment by Fleshgrinder** [comment]
No, don't be! It's actually very nice of you to keep testing and coming back, despite my incompetence to test correctly. I really should invest some time into learning some shunit2 scripting.

**Comment by barnumbirr** [comment]
> It's actually very nice of you to keep testing and coming back, [...]

Well that's what open-source software is all about, isn't it? :smile:
Name collision is now fixed but `compile.sh`hangs at `install -m 755 opentracker /usr/local/sbin``

Cheers.

**EDIT:** seems like there is no break out of this loop:

```
then
    install --mode=0755 -- "${__DIRNAME__}/opentracker" /etc/init.d
    update-rc.d opentracker defaults
fi
```

**Comment by Fleshgrinder** [comment]
That is because it is already installed and running, the file at `/usr/local/sbin/opentracker` is busy. Execute the following command `ps aux | grep opentracker`, this outputs the following on my VirtualBox:

``` shell
nobody  2442    0.0 0.2 26944   872 ?   S1  17:35   0:00    /usr/local/sbin/opentracker -f /etc/opentracker/opentracker.conf
root    2447    0.0 0.2 3560    808 tty1    S+  17:36   grep opentracker
```

The first line tells us that opentracker is already running. We could also issue `service opentracker status` which outputs `[ ok ] opentracker is running`. Now to stop it we simply issue `service opentracker stop` and to uninstall it from the system we do:

``` shell
rm --force -- /usr/local/sbin/opentracker
# Delete init script
rm --force -- /etc/init.d/opentracker
# Delete configuration
rm --force --recursive -- /etc/opentracker
```

Now you have a totally clean system again and can compile a new one. I will add a check to the script.

**Comment by Fleshgrinder** [comment]
Just realized that I already have that situation covered, the script does not hang on my side, even if opentracker is already running. Hmmm …

**Comment by Fleshgrinder** [comment]
What happens if you go to `/usr/local/src/opentracker` and issue `make install` yourself?

The line in the Makefile of opentracker only contains:

``` shell
install:
        install -m 755 opentracker $(BINDIR)
```

I cannot imagine how this command might hang. You could also try to issue that command by yourself: `install -m 755 opentracker /usr/local/sbin`

**Comment by barnumbirr** [comment]
Thank you very much, worked like a charm this time. :grin:

**Comment by Fleshgrinder** [comment]
Great! :+1: Open a new issue if you have any problems or questions.
